# Generated by Django 4.1.2 on 2022-11-29 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ucretler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=20, null=True)),
                ('ders_tarihi', models.DateField(null=True)),
                ('ders_saati', models.CharField(max_length=5, null=True)),
                ('fiyat', models.IntegerField(default=250, null=True, verbose_name='Ders ücreti')),
            ],
        ),
        migrations.CreateModel(
            name='Öğrenci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim_soyisim', models.CharField(max_length=25, verbose_name='İsim, Soyisim')),
            ],
        ),
        migrations.CreateModel(
            name='ÖzelDers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders_ad', models.CharField(max_length=25, verbose_name='Dersin adı')),
                ('ders_konu', models.CharField(max_length=50, verbose_name='Ders konu')),
                ('ders_tarihi', models.DateField()),
                ('ders_saati', models.CharField(max_length=5)),
                ('ders_yeri', models.CharField(blank=True, max_length=100, verbose_name='Ders yeri')),
                ('fiyat', models.IntegerField(default=250, verbose_name='Ders ücreti')),
                ('öğrenci', models.ForeignKey(blank=True, max_length=25, null=True, on_delete=django.db.models.deletion.CASCADE, to='özelders.öğrenci')),
            ],
        ),
    ]
