# Generated by Django 4.1.2 on 2022-12-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('özelders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UcretEmir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=20)),
                ('ders_tarihi', models.DateField(null=True)),
                ('ders_saati', models.CharField(max_length=5)),
                ('fiyat', models.IntegerField(default=250)),
            ],
        ),
    ]
