# Generated by Django 4.1.2 on 2022-12-02 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('özelders', '0002_ucretemir'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UcretEmir',
        ),
    ]
