# Generated by Django 4.1.2 on 2022-12-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('özelders', '0003_delete_ucretemir'),
    ]

    operations = [
        migrations.AddField(
            model_name='özelders',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
