# Generated by Django 4.1.2 on 2022-12-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('özelders', '0004_özelders_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='özelders',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
