# Generated by Django 4.1.3 on 2022-12-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('özelders', '0007_alter_özelders_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=20)),
                ('ders_tarihi', models.DateField()),
                ('ders_saati', models.CharField(max_length=5)),
                ('fiyat', models.CharField(default=250, max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='ucretler',
            name='ders_saati',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='ucretler',
            name='fiyat',
            field=models.IntegerField(default=250, max_length=3, verbose_name='Ders ücreti'),
        ),
        migrations.AlterField(
            model_name='ucretler',
            name='isim',
            field=models.CharField(max_length=20),
        ),
    ]
