# Generated by Django 4.1.3 on 2022-12-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('özelders', '0008_miray_alter_ucretler_ders_saati_alter_ucretler_fiyat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Berkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=20)),
                ('ders_tarihi', models.DateField()),
                ('ders_saati', models.CharField(max_length=5)),
                ('fiyat', models.CharField(default=250, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Ceren',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=20)),
                ('ders_tarihi', models.DateField()),
                ('ders_saati', models.CharField(max_length=5)),
                ('fiyat', models.CharField(default=250, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Dilara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=20)),
                ('ders_tarihi', models.DateField()),
                ('ders_saati', models.CharField(max_length=5)),
                ('fiyat', models.CharField(default=250, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Duru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=20)),
                ('ders_tarihi', models.DateField()),
                ('ders_saati', models.CharField(max_length=5)),
                ('fiyat', models.CharField(default=250, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Eflin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=20)),
                ('ders_tarihi', models.DateField()),
                ('ders_saati', models.CharField(max_length=5)),
                ('fiyat', models.CharField(default=250, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Emir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=20)),
                ('ders_tarihi', models.DateField()),
                ('ders_saati', models.CharField(max_length=5)),
                ('fiyat', models.CharField(default=250, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='İpek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=20)),
                ('ders_tarihi', models.DateField()),
                ('ders_saati', models.CharField(max_length=5)),
                ('fiyat', models.CharField(default=250, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Teoman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=20)),
                ('ders_tarihi', models.DateField()),
                ('ders_saati', models.CharField(max_length=5)),
                ('fiyat', models.CharField(default=250, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Zeynep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=20)),
                ('ders_tarihi', models.DateField()),
                ('ders_saati', models.CharField(max_length=5)),
                ('fiyat', models.CharField(default=250, max_length=3)),
            ],
        ),
    ]
