# Generated by Django 4.1.2 on 2022-11-21 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Kripto',
        ),
    ]
