# Generated by Django 4.1.2 on 2022-11-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_kripto_guncelleme_tarih_alter_kripto_tarih'),
    ]

    operations = [
        migrations.AddField(
            model_name='kripto',
            name='aktif',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
