# Generated by Django 4.1.2 on 2022-11-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_kripto_aktif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kripto',
            name='aktif',
            field=models.BooleanField(),
        ),
    ]
