# Generated by Django 4.1.2 on 2022-12-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_matematik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kripto',
            name='aciklama',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='kripto',
            name='resim',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='matematik',
            name='resim',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='yazilim',
            name='resim',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
