# Generated by Django 4.1.2 on 2022-12-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_kripto_aciklama_alter_kripto_resim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kripto',
            name='aciklama',
            field=models.TextField(max_length=1500),
        ),
    ]
