# Generated by Django 4.1.2 on 2022-12-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_kripto_slug_alter_matematik_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kripto',
            name='slug',
            field=models.SlugField(blank=True, default=' ', editable=False),
        ),
        migrations.AlterField(
            model_name='matematik',
            name='slug',
            field=models.SlugField(blank=True, default=' ', editable=False),
        ),
        migrations.AlterField(
            model_name='yazilim',
            name='slug',
            field=models.SlugField(blank=True, default=' ', editable=False),
        ),
    ]
